### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zoredeaxx** [xditya/TelegraphUploader#2]
Getting following error on uploading images

[ERROR/2023-02-19 06:26:50,205] telethon.client.updates: Unhandled exception on uploader
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "/app/bot.py", line 80, in uploader
    media_urls = upload_file(downloaded_file_name)
  File "/usr/local/lib/python3.9/site-packages/telegraph/upload.py", line 13, in upload_file
    r = TelegraphApi().upload_file(f)
  File "/usr/local/lib/python3.9/site-packages/telegraph/api.py", line 56, in upload_file
    response = self.session.post(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any fix is highly appreciated.

**Comment by xditya** [comment]
This should fix it, kindly try and let me know.
